# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Codoki
tagline:             'Tutorials, resources and tips for web developers and designers'
url:                 codoki.github.io
paginate:            10
baseurl:             /

# About/contact
author:
  name:              Chris Diana
  url:               https://chrisdianamedia.com
  email:             cdiana.media@gmail.com

# Custom vars
version:             1.0.0
github:
  repo:             https://github.com/codoki
